M48
; DRILL file {KiCad 8.0.8} date 2025-02-18T00:45:40-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-18T00:45:40-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X5.2049Y-3.945
X5.4982Y-3.945
T2
X4.358Y-4.035
X6.187Y-3.082
M30
