M48
; DRILL file {KiCad 9.0.0} date 2025-04-12T10:41:55+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-12T10:41:55+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X31.882Y40.015
X31.882Y36.015
T2
X6.757Y10.928
X18.187Y10.928
M30
